### PR TITLE
Migrating to Swift 5

### PR DESCRIPTION
**Pull request by Alexwings**

### CODE REVIEW

**Comment by weakfl** [comment]
You should probably update `s.swift_version` in `SwiftyPickerPopover.podspec` and `.swift-version` to `5.0` as well.

**Comment by Alexwings** [comment]
@weakfl Thank you for the suggestion. Already addressed the version bump up.

**Comment by weakfl** [comment]
@hsylife Could you merge this please?

**Comment by hsylife** [comment]
I'm sorry to make you late.
I will check it up and merge it into the master.

Give me some time.

**Pull request merged**
