### PR TITLE
Swift4

### PR DESCRIPTION
**Pull request by iosMaher**
new addition
change picker font
change picker color

.setFont()
.setColor()

[StringPickerPopoverClasses.zip](https://github.com/hsylife/SwiftyPickerPopover/files/1593541/StringPickerPopoverClasses.zip)

### CODE REVIEW

**Comment by hsylife** [comment]
Thank you, iosMaher.
Firstly you should make a commit, which includes your new code, on Git and push it onto your folded repository on GitHub.
Secondly I'd like you to make a pull request from your feature branch based on Swift 4 to my swift4 branch.

I believe that we can deal with these steps one by one.
If you have any questions, please ask me!

**Comment by iosMaher** [comment]
im trying to push the source its says :
remote: Permission to hsylife/SwiftyPickerPopover.git denied to iosMaher.
fatal: unable to access 'https://github.com/hsylife/SwiftyPickerPopover.git/': The requested URL returned error: 403

**Comment by hsylife** [comment]
@iosMaher 
OK. 
At first, you need to make your fork from the original repository. 
See [this document](https://opensource.guide/how-to-contribute/#opening-a-pull-request) in detail!

Best,
Yuta

**Comment by hsylife** [comment]
Thank you so much for your contributing, @iosMaher.
I've created another PR, which includes your ideas!

**Comment by hsylife** [comment]
Please see this:
https://github.com/hsylife/SwiftyPickerPopover/pull/71

**Pull request closed without merging**
